# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61udio.proto\x12\nstoryaudio\"\"\n\x0c\x41udioRequest\x12\x12\n\nstory_text\x18\x01 \x01(\t\"#\n\rAudioResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x32Y\n\x11StoryAudioService\x12\x44\n\rGenerateAudio\x12\x18.storyaudio.AudioRequest\x1a\x19.storyaudio.AudioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUDIOREQUEST']._serialized_start=27
  _globals['_AUDIOREQUEST']._serialized_end=61
  _globals['_AUDIORESPONSE']._serialized_start=63
  _globals['_AUDIORESPONSE']._serialized_end=98
  _globals['_STORYAUDIOSERVICE']._serialized_start=100
  _globals['_STORYAUDIOSERVICE']._serialized_end=189
# @@protoc_insertion_point(module_scope)
